baseURL = 'https://leavex.eu'
defaultContentLanguage = 'en'
title = 'Leave X - Protect Democracy'

enableRobotsTXT = true

[module]
    [[module.imports]]
    path = "github.com/jpanther/congo/v2"

[params]
    homepage.layout = "custom"
    colorScheme = "ocean"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
