baseURL = 'https://leavex.eu'
defaultContentLanguage = 'en'
title = 'Leave X - Protect Democracy'
theme = 'congo'

enableRobotsTXT = true

[params]
    homepage.layout = "custom"
    colorScheme = "ocean"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
