[[main]]
  name = "Réseau"
  pageRef = "network"
  weight = 20

[[main]]
  name = "À propos"
  pageRef = "about"
  weight = 30

[[main]]
name = "Languages"
weight = 999

  [main.params]
  action = "locale"
  icon = "translate"
  showName = false

[[main]]
  name = "Appearance"
  weight = 998
  [main.params]
    action = "appearance"
    icon = "sun"
    showName = false