[plausibleAnalytics]
  domain = "leavex.eu"

[article]
  showReadingTime = false

[assets]
  loadExtendedCSS = true

[appearance]
  showSwitch = true
  defaultMode = "auto"

[header]
  layout = "basic"